#include "ParseTable.h"

namespace xmlParser {

    ParseTable getParseTable() {
        ParseTable table;
        table[LBracket] = {{shift,     TableEntry{3}},
                           {error,     TableEntry{}},
                           {shift,     TableEntry{3}},
                           {error,     TableEntry{}},
                           {shift,     TableEntry{12}},
                           {reduction, TableEntry{-1, Replacement{A, {C}}}},
                           {shift,     TableEntry{3}},
                           {reduction, TableEntry{-1, Replacement{C, {Value}}}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {reduction, TableEntry{-1, Replacement{A, {A, A}}}},
                           {error,     TableEntry{}},
                           {reduction, TableEntry{-1, Replacement{C, {Value}}}},
                           {shift,     TableEntry{18}},
                           {reduction, TableEntry{-1, Replacement{L, {LBracket, D, RBracket}}}},
                           {error,     TableEntry{}},
                           {reduction, TableEntry{-1, Replacement{A, {L, A, R}}}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {reduction, TableEntry{-1, Replacement{R, {LBracket, Dash, D, RBracket}}}}
        };
        table[RBracket] = {{error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {shift,     TableEntry{15}},
                           {reduction, TableEntry{-1, Replacement{D, {TagValue}}}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {shift,     TableEntry{21}},
                           {error,     TableEntry{}},
                           {error,     TableEntry{}},
                           {shift,     TableEntry{23}},
                           {error,     TableEntry{}}
        };
        table[Dash] = {{error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {shift, TableEntry{16}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {shift, TableEntry{20}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}},
                       {error, TableEntry{}}
        };
        table[Value] = {{error,     TableEntry{}},
                        {error,     TableEntry{}},
                        {shift,     TableEntry{7}},
                        {error,     TableEntry{}},
                        {shift,     TableEntry{13}},
                        {reduction, TableEntry{-1, Replacement{A, {C}}}},
                        {shift,     TableEntry{7}},
                        {error,     TableEntry{}},
                        {error,     TableEntry{}},
                        {error,     TableEntry{}},
                        {error,     TableEntry{}},
                        {reduction, TableEntry{-1, Replacement{A, {A, A}}}},
                        {error,     TableEntry{}},
                        {reduction, TableEntry{-1, Replacement{C, {Value}}}},
                        {shift,     TableEntry{13}},
                        {reduction, TableEntry{-1, Replacement{L, {LBracket, C, RBracket}}}},
                        {error,     TableEntry{}},
                        {reduction, TableEntry{-1, {A, {L, A, R}}}},
                        {error,     TableEntry{}},
                        {error,     TableEntry{}},
                        {error,     TableEntry{}},
                        {error,     TableEntry{}},
                        {error,     TableEntry{}},
                        {reduction, TableEntry{-1, Replacement{R, {LBracket, Dash, D, RBracket}}}}
        };
        table[TagValue] = {{error, TableEntry{}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
                           {shift, TableEntry{9}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
                           {shift, TableEntry{9}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
                           {shift, TableEntry{9}},
                           {error, TableEntry{}},
                           {shift, TableEntry{9}},
                           {error, TableEntry{}},
                           {shift, TableEntry{9}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
                           {error, TableEntry{}},
        };
        table[EndOfFile] = {{error,     TableEntry{}},
                            {accept,    TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {reduction, TableEntry{-1, Replacement{S, {L, A, R}}}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}},
                            {reduction, TableEntry{-1, Replacement{R, {LBracket, Dash, D, RBracket}}}},
                            {error,     TableEntry{}},
                            {error,     TableEntry{}}
        };
        table[S] = {{shift, TableEntry{1}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}}
        };
        table[A] = {{error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{4}},
                    {error, TableEntry{}},
                    {error, TableEntry{11}},
                    {error, TableEntry{}},
                    {shift, TableEntry{14}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{11}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{11}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}}
        };
        table[L] = {{shift, TableEntry{2}},
                    {error, TableEntry{}},
                    {shift, TableEntry{6}},
                    {error, TableEntry{}},
                    {shift, TableEntry{6}},
                    {error, TableEntry{}},
                    {shift, TableEntry{6}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{6}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{6}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}}
        };
        table[R] = {{error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{10}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{17}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}}
        };
        table[C] = {{error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{5}},
                    {error, TableEntry{}},
                    {shift, TableEntry{5}},
                    {error, TableEntry{}},
                    {shift, TableEntry{5}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{5}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{5}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}}
        };
        table[D] = {{error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{8}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{8}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {shift, TableEntry{19}},
                    {error, TableEntry{}},
                    {shift, TableEntry{8}},
                    {error, TableEntry{}},
                    {shift, TableEntry{22}},
                    {error, TableEntry{}},
                    {error, TableEntry{}},
                    {error, TableEntry{}}
        };
        return table;
    }

}
